version: '3.3'
services:

  mysql:

    image: mysql:8.0

    # container_name: mysql_container

    # Setup mysql to use self-based hash password
    command: mysqld --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

    # Setup port mapping
    ports:
      - "3306:3306"
    
    # Setup environment variables
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: volleyballdb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_HOST: "%"

    # Setup volume to prevent data loss
    volumes:
      - mysql:/var/lib/mysql

    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: [node.labels.mysql == true]

    networks:
      - vbnetwork

    # restart: always

  # Setup phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0

    # container_name: phpmyadmin_container

    environment:
      PMA_HOST: mysql #old:172.17.0.1
      MYSQL_ROOT_PASSWORD: test
      MYSQL_PASSWORD: test
      MYSQL_USER: user

    links:
      - mysql:db

    ports:
      - 8000:80

    depends_on:
      - mysql

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.mysql == true]

    networks:
      - vbnetwork

networks:
  vbnetwork:
    external: true

volumes:
  mysql:
    external: true