version: '3'
services:

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      #Link the internal Docker IP and ports 5672/15672 to the external ports 5672/15672
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: "worker"
      RABBITMQ_DEFAULT_PASS: "worker"
      RABBITMQ_DEFAULT_VHOST: "/"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.rabbitmq == true]
    networks:
      - vbnetwork

  flower:
    image: mher/flower:0.9.5
    command: ["flower","--broker=amqp://worker:worker@rabbitmq","--port=5555"]
    ports:
      #docker publish port 5555 to 5555 
      - 5555:5555
    depends_on:
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.flower == true]
    networks:
      - vbnetwork

networks:
  vbnetwork:
    external: true